# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51ca5d74fa570aa74737e1871a08ab44ea8f6fc644a324408ce95301efc577d62ceb1530c17bc6c7e375ff457e7c2ed949fd55d78ac0c947f8f47a5204e89674

test:
  secret_key_base: e22316b6c54ac79a2fa1fa77e2d1cf0862739018c4eca607cbe8acbe66ef04c82899cd9c6dfc5bbe75ee3bf7d05cb31036aa4a67769e935a8caf77ce1c251614

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
